import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Urban Nocturne Design System — Dark Mode
        "background": "#081422",
        "surface": "#081422",
        "surface-dim": "#081422",
        "surface-bright": "#2f3a4a",
        "surface-container-lowest": "#040f1d",
        "surface-container-low": "#111c2b",
        "surface-container": "#15202f",
        "surface-container-high": "#202b3a",
        "surface-container-highest": "#2a3545",
        "surface-variant": "#2a3545",
        "on-background": "#d8e3f8",
        "on-surface": "#d8e3f8",
        "on-surface-variant": "#c0c8c7",
        "inverse-surface": "#d8e3f8",
        "inverse-on-surface": "#263141",
        "primary": "#a2cfce",
        "primary-container": "#003333",
        "primary-fixed": "#beebea",
        "primary-fixed-dim": "#a2cfce",
        "on-primary": "#043737",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#224d4d",
        "on-primary-container": "#719c9b",
        "inverse-primary": "#3b6565",
        "surface-tint": "#a2cfce",
        "secondary": "#f0be72",
        "secondary-container": "#674500",
        "secondary-fixed": "#ffddaf",
        "secondary-fixed-dim": "#f0be72",
        "on-secondary": "#432c00",
        "on-secondary-fixed": "#281800",
        "on-secondary-fixed-variant": "#614000",
        "on-secondary-container": "#e4b469",
        "tertiary": "#a3caf6",
        "tertiary-container": "#002f51",
        "tertiary-fixed": "#d0e4ff",
        "tertiary-fixed-dim": "#a3caf6",
        "on-tertiary": "#003256",
        "on-tertiary-fixed": "#001d35",
        "on-tertiary-fixed-variant": "#20496f",
        "on-tertiary-container": "#7298c2",
        "outline": "#8a9292",
        "outline-variant": "#404848",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      keyframes: {
        spin: { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },
        ping: { "75%, 100%": { transform: "scale(2)", opacity: "0" } },
        pulse: { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.5" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-up": { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out",
        "slide-up": "slide-up 0.3s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
