import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // The Ancient Explorer — Parchment / Ocre Design System
        "background": "#fff9ed",
        "surface": "#fff9ed",
        "surface-dim": "#f0e8d5",
        "surface-bright": "#fffcf5",
        "surface-container-lowest": "#fffef9",
        "surface-container-low": "#fdf5e4",
        "surface-container": "#f5ead6",
        "surface-container-high": "#ece0ca",
        "surface-container-highest": "#e2d4b8",
        "surface-variant": "#ddd0b3",
        "on-background": "#2c1a00",
        "on-surface": "#2c1a00",
        "on-surface-variant": "#5c4a2a",
        "inverse-surface": "#2c1a00",
        "inverse-on-surface": "#fff9ed",
        // Primary = ocre brun (bois, parchemin foncé)
        "primary": "#8c4b00",
        "primary-container": "#ffddb8",
        "primary-fixed": "#ffddb8",
        "primary-fixed-dim": "#c97a30",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#2e1500",
        "on-primary-fixed-variant": "#6a3800",
        "on-primary-container": "#2e1500",
        "inverse-primary": "#ffb96a",
        "surface-tint": "#8c4b00",
        // Secondary = teal sombre (encre, patine)
        "secondary": "#296767",
        "secondary-container": "#c0eaea",
        "secondary-fixed": "#c0eaea",
        "secondary-fixed-dim": "#4a8f8f",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#002020",
        "on-secondary-fixed-variant": "#004f4f",
        "on-secondary-container": "#002020",
        // Tertiary = rouge sépia (cachets, cire)
        "tertiary": "#8b2a00",
        "tertiary-container": "#ffdbd0",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#bf5a38",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#330e00",
        "on-tertiary-fixed-variant": "#6a1f00",
        "on-tertiary-container": "#330e00",
        "outline": "#8c7a5a",
        "outline-variant": "#cdbf9e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#410002",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-serif)", "Georgia", "serif"],
        body: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        label: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      keyframes: {
        spin: { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },
        ping: { "75%, 100%": { transform: "scale(2)", opacity: "0" } },
        pulse: { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.5" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-up": { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        "flicker": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.85" } },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out",
        "slide-up": "slide-up 0.3s ease-out",
        "flicker": "flicker 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
